const maleNames = [
  "Liam",
  "Noah",
  "Oliver",
  "Elijah",
  "James",
  "William",
  "Benjamin",
  "Lucas",
  "Henry",
  "Theodore",
  "Jack",
  "Levi",
  "Alexander",
  "Jackson",
  "Mateo",
  "Daniel",
  "Michael",
  "Mason",
  "Sebastian",
  "Ethan",
  "Logan",
  "Owen",
  "Samuel",
  "Jacob",
  "Asher",
  "Aiden",
  "John",
  "Joseph",
  "Wyatt",
  "David",
  "Leo",
  "Luke",
  "Julian",
  "Hudson",
  "Grayson",
  "Matthew",
  "Ezra",
  "Gabriel",
  "Carter",
  "Isaac",
  "Jayden",
  "Luca",
  "Anthony",
  "Dylan",
  "Lincoln",
  "Thomas",
  "Maverick",
  "Elias",
  "Josiah",
  "Charles",
  "Caleb",
  "Christopher",
  "Ezekiel",
  "Miles",
  "Jaxon",
  "Isaiah",
  "Andrew",
  "Joshua",
  "Nathan",
  "Nolan",
  "Adrian",
  "Cameron",
  "Santiago",
  "Eli",
  "Aaron",
  "Ryan",
  "Angel",
  "Cooper",
  "Waylon",
];

const lastNames = [
  "Solace",
  "Levine",
  "Thatcher",
  "Raven",
  "Bardot",
  "St. James",
  "Hansley",
  "Cromwell",
  "Ashley",
  "Monroe",
  "West",
  "Langley",
  "Daughtler",
  "Madison",
  "Marley",
  "Ellis",
  "Hope",
  "Cassidy",
  "Lopez",
  "Jenkins",
  "Poverly",
  "McKenna",
  "Gonzales",
  "Collymore",
  "Stoll",
  "Verlice",
  "Adler",
  "Huxley",
  "Ledger",
  "Hayes",
  "Ford",
  "Finnegan",
  "Beckett",
  "Gatlin",
  "Pierce",
  "Zimmerman",
  "Dawson",
  "son",
  "Adair",
  "Gray",
];

let femaleNames = [
  "Olivia",
  "Emma",
  "Charlotte",
  "Amelia",
  "Ava",
  "Sophia",
  "Isabella",
  "Mia",
  "Evelyn",
  "Harper",
  "Luna",
  "Camila",
  "Gianna",
  "Elizabeth",
  "Eleanor",
  "Ella",
  "Abigail",
  "Sofia",
  "Avery",
  "Scarlett",
  "Emily",
  "Aria",
  "Penelope",
  "Chloe",
  "Layla",
  "Mila",
  "Nora",
  "Hazel",
  "Madison",
  "Ellie",
  "Lily",
  "Nova",
  "Isla",
  "Grace",
  "Violet",
  "Aurora",
  "Riley",
  "Zoey",
  "Willow",
  "Emilia",
  "Stella",
  "Zoe",
  "Victoria",
  "Hannah",
  "Addison",
  "Leah",
  "Lucy",
  "Eliana",
  "Ivy",
  "Everly",
  "Lillian",
  "Paisley",
  "Elena",
  "Naomi",
  "Maya",
  "Natalie",
  "Kinsley",
  "Delilah",
  "Claire",
  "Audrey",
  "Aaliyah",
  "Ruby",
  "Brooklyn",
  "Alice",
  "Aubrey",
  "Autumn",
  "Leilani",
  "Savannah",
  "Valentina",
  "Kennedy",
];

const name = document.querySelector(".name");
const button = document.querySelector(".generate");
const nameSelect = document.querySelector("#gender");
let generateName;

function generateMaleName() {
  let generateName = `${
    maleNames[Math.floor(Math.random() * maleNames.length)]
  } ${lastNames[Math.floor(Math.random() * lastNames.length)]}`;
  name.textContent = generateName;
}

function generateFemaleName() {
  let generateName = `${
    femaleNames[Math.floor(Math.random() * femaleNames.length)]
  } ${lastNames[Math.floor(Math.random() * lastNames.length)]}`;
  name.textContent = generateName;
}

button.addEventListener("click", function () {
  let nameSelectValue = nameSelect.options[nameSelect.selectedIndex].value;

  nameSelectValue === "Male" ? generateMaleName() : generateFemaleName();
});
